services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: $(POSTGRES_DB)
      POSTGRES_USER: $(POSTGRES_USER)
      POSTGRES_PASSWORD: $(POSTGRES_PASSWORD)
    volumes:
      - db_data:/var/lib/postgresql/db
volumes:
  db_data: